# Site settings
title: DataQuest
email: ahmedtadde@gmail.com
description: Exploring, discovering and "charting" the Dataverse
baseurl: /DataQuest
username: ahmedtadde
include: ["_pages"]

category: [visualization, writeups, other, tags, archive]
collections:
  about:
    output: false
  blog:
    output: true
  projects:
    output: true
  resume:
    output: false

# Build settings
timezone: America/New York
markdown: kramdown
redcarpet:
    extensions: [with_toc_data]  # to add id to headers

permalink: /blog/:categories/:year/:month/:day/:title
